### ISSUE TITLE
Variable Label error

### ISSUE THREAD

**Issue by githubheyguy** [SkalskiP/yolov8-live#2]
labels = [
            f"{model.model.names[class_id]} {confidence:0.2f}"
            for _, confidence, class_id, _
            in detections
        ]
        
    for _, confidence, class_id, _
ValueError: too many values to unpack (expected 4)

**Comment by SkalskiP** [comment]
You didn’t use requirements.txt to install.

**Comment by sarah-tujjar** [comment]
Traceback (most recent call last):
  File "main.py", line 83, in <module>
    main()
  File "main.py", line 61, in main
    labels = [
  File "main.py", line 61, in <listcomp>
    labels = [
ValueError: too many values to unpack (expected 4)

I activated the virtual environment and used  requirements.txt to install but still getting this error'

**Comment by SkalskiP** [comment]
Hi @malin-howto and @sarah-tujjar 👋🏻 It looks like you have an incorrect version of `supervision` installed. Try to downgrade supervision to `0.2.1`.

**Comment by Ryandran** [comment]
I have the same problems :
0: 384x640 1 person, 1 chair, 1162.7ms
Speed: 4.0ms preprocess, 1162.7ms inference, 3.0ms postprocess per image at shape (1, 3, 384, 640)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Yolov8-counting\main.py", line 81, in <module>
    main()
  File "C:\Yolov8-counting\main.py", line 60, in main
    labels = [
             ^
  File "C:\Yolov8-counting\main.py", line 62, in <listcomp>
    for _, confidence, class_id, _
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 4)

**Comment by Ryandran** [comment]
Problem solved :
labels = [
            f"{model.model.names[class_id]} {confidence:0.2f}"
            for _, _, confidence, class_id, _ in detections
        ]

**Comment by SkalskiP** [comment]
Hi @Ryandran 👋🏻 That's an alternative solution. Assuming you want to change the code ;)
